import { useEffect, useState } from 'react';
import './quest.css';
const icons={stage:'🗺️',review:'🧠',interview:'⚔️',demon:'👹'};
async function api(path,options){const response=await fetch(path,{...options,headers:{'content-type':'application/json',...options?.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;}
export default function DailyCenter({onForest,onFramework,onReview,onDemon,onInterview}){
 const [daily,setDaily]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let live=true;api('/api/quest/daily').then(data=>{if(live)setDaily(data);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 async function claim(id){if(busy)return;setBusy(true);setError('');try{const result=await api(`/api/quest/daily/${id}/claim`,{method:'POST',body:'{}'});setMessage(result.earnedXp?`领取成功，获得 ${result.earnedXp} XP。`:'这项奖励已经领取。');setDaily(await api('/api/quest/daily'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <main className="quest-hub"><div className="quest-hub-inner"><header className="quest-hub-header"><div><span className="quest-hub-eyebrow">NOWEN · DAILY QUESTS V0.6</span><h1>今日修炼</h1><p>按你的日历时区完成每日任务，不打卡也不会掉级。</p></div></header>{error&&<p className="quest-hub-alert" role="alert">{error}</p>}{!daily?<p role="status">正在读取每日任务…</p>:<section className="quest-daily"><div className="quest-daily-summary"><div><span>DAILY QUESTS · {daily.day} · {daily.timeZone}</span><h2>已完成 {daily.completed} / {daily.tasks.length} 项</h2><p>依据两座世界的通关、记忆自评和完整面试记录统计，奖励不可重复领取。</p></div><div className="quest-daily-ring">{daily.completed}<small>/ {daily.tasks.length}</small></div></div><div className="quest-daily-list">{daily.tasks.map(task=><div className="quest-daily-item" key={task.id}><span className="quest-daily-icon">{icons[task.id]}</span><div className="quest-daily-copy"><strong>{task.title}</strong><p>{task.description}</p><small>{task.progress}/{task.goal} · 奖励 {task.xp} XP</small></div><button disabled={busy||task.claimed||!task.completed} onClick={()=>claim(task.id)}>{task.claimed?'✓ 已领取':task.completed?'领取奖励':'待完成'}</button></div>)}</div>{message&&<p className="quest-hub-success" role="status">{message}</p>}<div className="quest-daily-quick"><button onClick={onForest}>🌲 JavaScript 森林</button><button onClick={onFramework}>🏝️ React 群岛</button><button onClick={onReview}>🧠 记忆修炼</button><button onClick={onDemon}>👹 心魔讨伐</button><button onClick={onInterview}>⚔️ 模拟面试</button></div><p className="quest-hub-note">{daily.notice}</p></section>}</div></main>;
}
